import math

STEP_SIZE=0.5
MAX_ANGLE_CHANGE=math.pi/8 # Radians
MAX_SPEED_CHANGE=0.1
GAMMA = 0.9 # Reward decay
# Reward
DISTANCE_SCALE = 1e-3
COLLISION_SCALE = 1e-2
TIME_SCALE = 1e-4
SUCCESS_REWARD = 10